%feature("docstring") OT::ActiveLearningGMMFunction
R"RAW(Active learning criterion for reliability analysis implementing the Generalized Max Min function.

.. warning::
    This class is experimental and likely to be modified in future releases.
    To use it, import the ``openturns.experimental`` submodule.

Let :math:`\inputRV_1, \dots, \inputRV_n` be the samples of dimension :math:`\inputDim` generated by the simulation algorithm, :math:`T` the event threshold and :math:`\widehat{\model}(\cdot)` the mean of the conditioned Gaussian process. The selected samples for infill criterion evaluation are selected according to a criterion based on the quantile of the samples formed by the scaled outputs, given by :math:`\left\{\forall i \in \left\{1, \dots, n\right\} |\widehat{\model}(\inputRV_i) - T|\right\}`.
Let :math:`\inputRV_{{DOE}_1}, \dots, \inputRV_{{DOE}_{n_{DOE}}}` be the current input Design of Experiments.
Consider :math:`\vect{X}_i` a sample selected for infill criterion evaluation and :math:`f_{\inputRV}(\inputRV_i)` the value of the input vector PDF on the selected sample. The Generalized Max Min (GMM) function  :math:`GMM: \Rset^{\inputDim} \rightarrow \Rset^{+}` is defined as the minimal distance to the DoE weighted by the PDF of the input vector:

.. math::

   GMM(\inputRV_i)=f_{\inputRV}(\inputRV_i)^{1/d} \min_{j=1,...,n_{DOE}} \|\inputRV_i - \inputRV_{{DOE}_j}\|

The sample that maximizes the GMM criterion will be selected for infill.

The quantile prefilter is relative to the evaluated sample: evaluate
the criterion on the whole candidate pool at once, not point by point
(a single-point evaluation can never exceed its own quantile).

Unlike the U and EFF criteria, this composite criterion has no external
literature reference: the definition above is its complete specification.

Parameters
----------
reliabilityThreshold : float
    Reliability analysis threshold.

learningThreshold : float
    Threshold used to check the active learning convergence.

inputDistribution : Distribution
    Probability distribution of the input variables.

outputQuantileLevel : float
    Quantile level of the samples that will be considered for infill. 

See also
--------
ActiveLearningUFunction, ActiveLearningEFFFunction, ActiveLearningReliabilityFunction, ActiveLearningReliabilityAlgorithm
)RAW"
