%feature("docstring") OT::ActiveLearningReliabilityAlgorithm
R"RAW(Active learning reliability algorithm.

Parameters
----------

gpFitter : :class:`~openturns.GaussianProcessFitter`
    Gaussian process fitter (not trained)

simulationAlgorithm : probability simulation algorithm
    Probability simulation algorithm

activeLearningFunction : :class:`~ActiveLearningReliabilityFunction`
    Active learning function

simulationBudget : int
    Maximal number of true function calls for active learning

See also
--------
ActiveLearningGMMFunction, ActiveLearningEFFFunction, ActiveLearningUFunction, ActiveLearningReliabilityResult

Notes
-----
Let consider the following reliability analysis problem to solve: 
:math:`P_f = \Prob{\model\left( \inputRV \right) \leq T)}`

:math:`\inputRV` is the input random vector of dimension :math:`\inputDim`, :math:`f_\inputRV (\mathbf{x})`  its joint density probability function. :math:`\model(\cdot)` is the limit state function of the model. 
:math:`D_f = \{\inputRV \in \mathbb{R}^\inputDim \, \vert \, \model(\inputRV,\mathbf{d}) \leq T\}` is the domain definition of the event to consider (failure). :math:`\model(\cdot) = T` is called the limit state.

The failure condition can also be :math:`\model(\inputRV)\geq T`, see :class:`~openturns.ThresholdEvent`.

The probability of failure can be defined as follows : 
:math:`P_f = \Prob{\model(\inputRV)\leq T}=   \int_{D_f}  f_\inputRV(\mathbf{x}) d\mathbf{x}`

This probability can also be written as : 
:math:`P_f = \int_{\mathbb{R}^{\inputDim}}  \mathbf{1}_{ \left\{ \model(\inputRV) \leq T \right\} }f_\inputRV(\mathbf{x}) d\mathbf{x}`

In case of reliability analysis involving numerically costly simulation code, one may be interested in substituting :math:`\model(\cdot)` by a metamodel that is cheaper to evaluate. Active-learning reliability analysis consists in substituting the limit state function by a surrogate model (often a Gaussian process regressor) and refining the surrogate model for the reliability analysis purpose. In case of threshold event simulation, the surrogate model has to be accurate in the zones that are relevant to the failure probability estimation i.e., in the vicinity of threshold :math:`T` 
and in the high probability content regions. The use of the exact function :math:`\model` and its surrogate :math:`\hat{\model}` in the probability calculation will lead to the same result if 
:math:`\forall \mathbf{x} \in \mathbb{R}^{\inputDim}, \mathbf{1}_{\model(\mathbf{x})<T} = \mathbf{1}_{\hat{\model}(\mathbf{x})<T}` with :math:`\hat{\model}` the surrogate model of :math:`\model`. 

Active-learning methods consist in refining only the samples (generated by the simulation algorithm) that are uncertain with respect the threshold crossing in order to limit the uncertainty provided by the metamodel to the failure probability. The goal is to minimize the number of samples that have to be evaluated on the simulation code in the probability simulation.

From the initial training set :math:`\mathcal{X}`, the Gaussian process properties (i.e. estimation of the predicted error variance) are valuable to determine the additional samples which have to be evaluated on $\model(\cdot)$ to refine the surrogate model. Different refinement strategies have been developed in the literature.

The :class:`~openturns.ActiveLearningReliabilityAlgorithm` allows one to couple different simulation algorithms ( :class:`~openturns.ProbabilitySimulationAlgorithm` using :class:`~openturns.MonteCarloExperiment`, :class:`~openturns.NAIS`, :class:`~openturns.StandardSpaceCrossEntropyImportanceSampling`, :class:`~openturns.PhysicalSpaceCrossEntropyImportanceSampling` or :class:`~openturns.SubsetSampling`) with dedicated refinement criteria (also named as infill criteria, see :class:`~openturns.ActiveLearningUFunction`, :class:`~openturns.ActiveLearningEFFFunction` or :class:`~openturns.ActiveLearningGMMFunction`).

The :class:`~openturns.ActiveLearningReliabilityAlgorithm` offers a unified API for testing  all the reliability algorithms and infill criteria. Different stopping criteria have also been implemented.

The main usage of :class:`~openturns.ActiveLearningReliabilityAlgorithm` is composed of different steps that are:

0 - Define of a Design of Experiments (DoE) and evaluate of the simulation code

1 - Train a Gaussian Process Regressor (GPR) on the current DoE

2 - Perform a probability simulation on the GPR

3 - Evaluate the samples retrieved by the probability simulation algorithm on an infill criterion

4 - Select the most informative sample based on the infill criterion

5 - Evaluate the simulation code on this sample

6 - Update the DoE and retrain the GPR

7 - Check a convergence criterion

The steps 2 to 7 are repeated until convergence. 

Different stopping criteria have been implemented. The first one is based on the simulation budget (maximal number of calls of the simulation code). The second one is based on the infill criterion (see :class:`~openturns.ActiveLearningUFunction`, :class:`~openturns.ActiveLearningEFFFunction` or :class:`~openturns.ActiveLearningGMMFunction`). The third one is based on the uncertainty of probability (or reliability index) due to the use of the GPR. The fourth one is based on the stability of the probability estimate (or reliability index) between two iterations of the active learning reliability algorithm. The convergence criterion can be set with the `setConvergenceCriterion` method, with dedicated flags:

- `PROBABILITY_UNCERTAINTY` : convergence based on the uncertainty of probability estimate due to the Gaussian process

- `RELIABILITY_INDEX_UNCERTAINTY` : convergence based on the uncertainty of reliability index estimate due to the Gaussian process

- `ACTIVE_LEARNING` : convergence based on the active learning

- `PROBABILITY_STABILITY` : convergence based on the stability of probability estimate between two active learning iterations

- `RELIABILITY_INDEX_STABILITY` : convergence based on the stability of probability estimate between two active learning iterations

)RAW"

// ---------------------------------------------------------------------------
%feature("docstring") OT::ActiveLearningReliabilityAlgorithm::setConvergenceCriterion
"Accessor to convergence criterion.

Parameters
----------
convergenceCriterion : int, optional
    Selection flag:

    - PROBABILITY_UNCERTAINTY : convergence based on the uncertainty of probability estimate due to the Gaussian process
    - RELIABILITY_INDEX_UNCERTAINTY : convergence based on the uncertainty of reliability index estimate due to the Gaussian process
    - ACTIVE_LEARNING : convergence based on the active learning
    - PROBABILITY_STABILITY : convergence based on the stability of probability estimate between two active learning iterations
    - RELIABILITY_INDEX_STABILITY : convergence based on the stability of probability estimate between two active learning iterations
"

// ---------------------------------------------------------------------------
%feature("docstring") OT::ActiveLearningReliabilityAlgorithm::setConvergenceCriterionThreshold
"Accessor to the convergence uncertainty threshold. This parameter is used to check the convergence (regarding probabiliy uncertainty, reliability index uncertainty, probability stability or reliability index stability.

Parameters
----------
convergenceCriterionThreshold : Scalar
   Threshold to check is active learning reliability algorithm has converged

Notes
-----
This unique accessor allows one to define the threshold to check convergence in case `PROBABILITY_UNCERTAINTY`, `RELIABILITY_INDEX_UNCERTAINTY`,
`PROBABILITY_STABILITY` or `RELIABILITY_INDEX_STABILITY` are selected in method `setConvergenceCriterion`
"

// ---------------------------------------------------------------------------
%feature("docstring") OT::ActiveLearningReliabilityAlgorithm::setConvergenceUncertaintyFactor
"Accessor to the convergence uncertainty factor. This parameter is used to determine the confidence interval of probability due to Gaussian process uncertainty. The default value is set to the `ActiveLearningReliabilityAlgorithm-DefaultConvergenceUncertaintyFactor` entry from :class:`~openturns.ResourceMap`.

Parameters
----------
convergenceUncertaintyFactor : Scalar
   Convergence uncertainty factor

Notes
-----
This parameter :math:`k` is used to determine the confidence interval of probability due to Gaussian process uncertainty. This term is a multiplicative factor of  the standard deviation of the Gaussian process to compute the confidence interval. Let consider :math:`\inputRV` the input random vector and :math:`T` the threshold defining the limit state of the reliability problem, and :math:`\hat{\model}(\cdot)` and :math:`\hat{\sigma}(\cdot)` respectively the mean and standard deviation of the conditioned Gaussian process used in the :class:`~openturns.ActiveLearningReliabilityAlgorithm`. The convergence uncertainty factor is used when the convergence criterion is equal to `PROBABILITY_UNCERTAINTY` and `RELIABILITY_INDEX_UNCERTAINTY` and computes the probability for :math:`\hat{\model}(\cdot)+/- k \hat{\sigma}(\cdot)` instead of :math:`\hat{\model}(\cdot)`
"

// ---------------------------------------------------------------------------
%feature("docstring") OT::ActiveLearningReliabilityAlgorithm::setSimulationBudget
"Accessor to maximal simulation budget.

Parameters
----------
simulationBudget : int
   Maximal simulation budget
"

// ---------------------------------------------------------------------------
%feature("docstring") OT::ActiveLearningReliabilityAlgorithm::setSimulationAlgorithmSeed
"Accessor to random generator seed for the simulation algorithm. The default value is set to the `ActiveLearningReliabilityAlgorithm-DefaultSimulationAlgorithmSeed` entry from :class:`~openturns.ResourceMap`.

Parameters
----------
seed : int
   Seed of the random generator
"

// ---------------------------------------------------------------------------
%feature("docstring") OT::ActiveLearningReliabilityAlgorithm::getSimulationAlgorithmSeed
"Accessor to random generator seed for the simulation algorithm.

Returns
-------
seed : int
   Seed of the random generator
"


// ---------------------------------------------------------------------------
%feature("docstring") OT::ActiveLearningReliabilityAlgorithm::getSimulationAlgorithm
"Accessor to simulation algorithm.

Returns
-------
simulationAlgorithm : pointer to the simulation algorithm. This is temporary
   Simulation algorithm
"


// ---------------------------------------------------------------------------
%feature("docstring") OT::ActiveLearningReliabilityAlgorithm::getFunctionCallNumber
"Accessor to number of limit state function calls

Returns
-------
functionCall : int
   Number of limit state function calls
"

// ---------------------------------------------------------------------------
%feature("docstring") OT::ActiveLearningReliabilityAlgorithm::getInputDoE
"Accessor to Design of experiments input sample

Returns
-------
functionCall : :class:`~openturns.Sample`
   Design of experiments, input sample
"

// ---------------------------------------------------------------------------
%feature("docstring") OT::ActiveLearningReliabilityAlgorithm::getOutputDoE
"Accessor to Design of experiments output sample

Returns
-------
functionCall : :class:`~openturns.Sample`
   Design of experiments, output sample
"

// ---------------------------------------------------------------------------
%feature("docstring") OT::ActiveLearningReliabilityAlgorithm::getResult
"Accessor to Active Reliability algorithm result

Returns
-------
functionCall : :class:`~openturns.ActiveLearningReliabilityResult`
   Result of active learning algorithm
"
