%define OT_CombinatorialGenerator_doc
"Combinatorial generator base class.

See also
--------
Combinations, KPermutations, Tuples"
%enddef
%feature("docstring") OT::CombinatorialGeneratorImplementation
OT_CombinatorialGenerator_doc

// ---------------------------------------------------------------------

%define OT_CombinatorialGenerator_generateNext_doc
"Generate the next element of the combinatorial sequence.

Returns
-------
indices : :class:`~openturns.Indices`
    The next element of the sequence. The order in which the elements are
    generated depends on the concrete generator.

Notes
-----
The generator holds an internal state, as :class:`~openturns.SplitterImplementation` does.
:any:`restart` starts the sequence over from its beginning.
Once all the :any:`getSize` elements have been generated,
calling this method raises an exception.
In Python, the generator can also be iterated over directly::

    for indices in ot.Combinations(2, 5):
        print(indices)"
%enddef
%feature("docstring") OT::CombinatorialGeneratorImplementation::generateNext
OT_CombinatorialGenerator_generateNext_doc

// ---------------------------------------------------------------------

%define OT_CombinatorialGenerator_getSize_doc
"Get the number of elements of the combinatorial sequence.

Returns
-------
size : int
    The number of total elements generated,
    without building the whole collection."
%enddef
%feature("docstring") OT::CombinatorialGeneratorImplementation::getSize
OT_CombinatorialGenerator_getSize_doc

// ---------------------------------------------------------------------

%define OT_CombinatorialGenerator_getDimension_doc
"Get the dimension of the generated indices.

Returns
-------
dimension : int
    The size of each :class:`~openturns.Indices` generated by
    :any:`generateNext`."
%enddef
%feature("docstring") OT::CombinatorialGeneratorImplementation::getDimension
OT_CombinatorialGenerator_getDimension_doc

// ---------------------------------------------------------------------

%define OT_CombinatorialGenerator_restart_doc
"Restart the combinatorial sequence from its beginning.

Notes
-----
The next call to :any:`generateNext` (or to the Python iterator)
generates the first element of the sequence again."
%enddef
%feature("docstring") OT::CombinatorialGeneratorImplementation::restart
OT_CombinatorialGenerator_restart_doc
