// SWIG file OrthogonalUniVariateFunctionFamily.i

%{
#include "openturns/OrthogonalUniVariateFunctionFamily.hxx"
%}

%include OrthogonalUniVariateFunctionFamily_doc.i

OTDefaultCollectionConvertFunctionsMisnamed(OrthogonalUniVariateFunctionFamily, OrthogonalUniVariateFunctionFactory)

OTTypedInterfaceObjectImplementationHelper(OrthogonalUniVariateFunctionFamily, OrthogonalUniVariateFunctionFactory)
OTTypedCollectionInterfaceObjectMisnamedHelper(OrthogonalUniVariateFunctionFamily, UniVariateFunctionFamilyCollection)

%copyctor OT::OrthogonalUniVariateFunctionFamily;
%include openturns/OrthogonalUniVariateFunctionFamily.hxx

