// SWIG file OrthogonalUniVariatePolynomialFamily.i

%{
#include "openturns/OrthogonalUniVariatePolynomialFamily.hxx"
%}

%include OrthogonalUniVariatePolynomialFamily_doc.i

OTDefaultCollectionConvertFunctionsMisnamed(OrthogonalUniVariatePolynomialFamily, OrthogonalUniVariatePolynomialFactory)

OTTypedInterfaceObjectImplementationHelper(OrthogonalUniVariatePolynomialFamily, OrthogonalUniVariatePolynomialFactory)
OTTypedCollectionInterfaceObjectMisnamedHelper(OrthogonalUniVariatePolynomialFamily, PolynomialFamilyCollection)

%copyctor OT::OrthogonalUniVariatePolynomialFamily;

%include openturns/OrthogonalUniVariatePolynomialFamily.hxx
