// SimulationAlgorithm docstrings are defined in SimulationAlgorithmImplementation_doc.i

%feature("docstring") OT::SimulationAlgorithm
OT_SimulationAlgorithmImplementation_doc
%feature("docstring") OT::SimulationAlgorithm::getBlockSize
OT_SimulationAlgorithmImplementation_getBlockSize_doc
%feature("docstring") OT::SimulationAlgorithm::setBlockSize
OT_SimulationAlgorithmImplementation_setBlockSize_doc
%feature("docstring") OT::SimulationAlgorithm::getMaximumCoefficientOfVariation
OT_SimulationAlgorithmImplementation_getMaximumCoefficientOfVariation_doc
%feature("docstring") OT::SimulationAlgorithm::setMaximumCoefficientOfVariation
OT_SimulationAlgorithmImplementation_setMaximumCoefficientOfVariation_doc
%feature("docstring") OT::SimulationAlgorithm::getMaximumOuterSampling
OT_SimulationAlgorithmImplementation_getMaximumOuterSampling_doc
%feature("docstring") OT::SimulationAlgorithm::setMaximumOuterSampling
OT_SimulationAlgorithmImplementation_setMaximumOuterSampling_doc
%feature("docstring") OT::SimulationAlgorithm::getMaximumStandardDeviation
OT_SimulationAlgorithmImplementation_getMaximumStandardDeviation_doc
%feature("docstring") OT::SimulationAlgorithm::setMaximumStandardDeviation
OT_SimulationAlgorithmImplementation_setMaximumStandardDeviation_doc
%feature("docstring") OT::SimulationAlgorithm::run
OT_SimulationAlgorithmImplementation_run_doc
%feature("docstring") OT::SimulationAlgorithm::setProgressCallback
OT_SimulationAlgorithmImplementation_setProgressCallback_doc
%feature("docstring") OT::SimulationAlgorithm::setStopCallback
OT_SimulationAlgorithmImplementation_setStopCallback_doc
%feature("docstring") OT::SimulationAlgorithm::getConvergenceStrategy
OT_SimulationAlgorithmImplementation_getConvergenceStrategy_doc
%feature("docstring") OT::SimulationAlgorithm::setConvergenceStrategy
OT_SimulationAlgorithmImplementation_setConvergenceStrategy_doc
%feature("docstring") OT::SimulationAlgorithm::setMaximumTimeDuration
OT_SimulationAlgorithmImplementation_setMaximumTimeDuration_doc
%feature("docstring") OT::SimulationAlgorithm::getMaximumTimeDuration
OT_SimulationAlgorithmImplementation_getMaximumTimeDuration_doc
