// SobolIndicesAlgorithm docstrings are defined in SobolIndicesAlgorithmImplementation_doc.i.in

%feature("docstring") OT::SobolIndicesAlgorithm
OT_SobolIndicesAlgorithm_doc
%feature("docstring") OT::SobolIndicesAlgorithm::getFirstOrderIndices
OT_SobolIndicesAlgorithm_getFirstOrderIndices_doc
%feature("docstring") OT::SobolIndicesAlgorithm::getFirstOrderIndicesInterval
OT_SobolIndicesAlgorithm_getFirstOrderIndicesInterval_doc
%feature("docstring") OT::SobolIndicesAlgorithm::getAggregatedFirstOrderIndices
OT_SobolIndicesAlgorithm_getAggregatedFirstOrderIndices_doc
%feature("docstring") OT::SobolIndicesAlgorithm::getAggregatedTotalOrderIndices
OT_SobolIndicesAlgorithm_getAggregatedTotalOrderIndices_doc
%feature("docstring") OT::SobolIndicesAlgorithm::getSecondOrderIndices
OT_SobolIndicesAlgorithm_getSecondOrderIndices_doc
%feature("docstring") OT::SobolIndicesAlgorithm::getTotalOrderIndices
OT_SobolIndicesAlgorithm_getTotalOrderIndices_doc
%feature("docstring") OT::SobolIndicesAlgorithm::getTotalOrderIndicesInterval
OT_SobolIndicesAlgorithm_getTotalOrderIndicesInterval_doc
%feature("docstring") OT::SobolIndicesAlgorithm::getConfidenceLevel
OT_SobolIndicesAlgorithm_getConfidenceLevel_doc
%feature("docstring") OT::SobolIndicesAlgorithm::setConfidenceLevel
OT_SobolIndicesAlgorithm_setConfidenceLevel_doc
%feature("docstring") OT::SobolIndicesAlgorithm::getBootstrapSize
OT_SobolIndicesAlgorithm_getBootstrapSize_doc
%feature("docstring") OT::SobolIndicesAlgorithm::setBootstrapSize
OT_SobolIndicesAlgorithm_setBootstrapSize_doc
%feature("docstring") OT::SobolIndicesAlgorithm::draw
OT_SobolIndicesAlgorithm_draw_doc
%feature("docstring") OT::SobolIndicesAlgorithm::getUseAsymptoticDistribution
OT_SobolIndicesAlgorithm_getUseAsymptoticDistribution_doc
%feature("docstring") OT::SobolIndicesAlgorithm::setUseAsymptoticDistribution
OT_SobolIndicesAlgorithm_setUseAsymptoticDistribution_doc
%feature("docstring") OT::SobolIndicesAlgorithm::getFirstOrderIndicesDistribution
OT_SobolIndicesAlgorithm_getFirstOrderIndicesDistribution_doc
%feature("docstring") OT::SobolIndicesAlgorithm::getTotalOrderIndicesDistribution
OT_SobolIndicesAlgorithm_getTotalOrderIndicesDistribution_doc
%feature("docstring") OT::SobolIndicesAlgorithm::setDesign
OT_SobolIndicesAlgorithm_setDesign_doc
%feature("docstring") OT::SobolIndicesAlgorithm::DrawImportanceFactors
OT_SobolIndicesAlgorithm_DrawImportanceFactors_doc
%feature("docstring") OT::SobolIndicesAlgorithm::DrawSobolIndices
OT_SobolIndicesAlgorithm_DrawSobolIndices_doc
%feature("docstring") OT::SobolIndicesAlgorithm::DrawCorrelationCoefficients
OT_SobolIndicesAlgorithm_DrawCorrelationCoefficients_doc
