// SWIG file UncertaintyModelCopulaCollection.i

OTDefaultCollectionConvertFunctions(Distribution)
OTDefaultCollectionConvertFunctionsMisnamed(DistributionFactory, DistributionImplementationFactory)

