// SWIG file UncertaintyModelCopulaCollection.i

OTDefaultCollectionConvertFunctions(Distribution)
OTDefaultCollectionConvertFunctionsMisnamed(DistributionFactory, DistributionFactoryImplementation)

