%feature("docstring") OT::UniVariateDistributionPolynomialFactory
R"RAW(Build orthonormal or orthogonal univariate polynomial families.

.. warning::
    This class is experimental and likely to be modified in future releases.
    To use it, import the ``openturns.experimental`` submodule.

Parameters
----------
arg : :class:`~openturns.Distribution` or :class:`~openturns.OrthonormalizationAlgorithm`
    Either a :class:`~openturns.Distribution` implementing the probability
    measure according to which the polynomial family is orthonormal **or** an
    :class:`~openturns.OrthonormalizationAlgorithm`.

    In the first case, the implementation will switch to the suitable specific
    orthonormal univariate polynomial family if any (see the notes below), or
    it will default to the :class:`~openturns.AdaptiveStieltjesAlgorithm` to build
    an orthonormal univariate polynomial family.

Notes
-----
Use this functionality with caution:

   - The polynomials exist if and only if the distribution admits finite
     moments of all orders. Even if some algorithms manage to compute something, it
     will be plain numerical noise.
   - Even if the polynomials exist, they form a Hilbertian basis with respect to the
     dot product induced by the distribution if and only if the distribution is
     **determinate**, i.e., is characterized by its moments. For example, the
     :class:`~openturns.LogNormal` distribution has orthonormal polynomials of
     arbitrary degree but the projection onto the functional space generated by
     these polynomials (see :class:`~openturns.FunctionalChaosAlgorithm`) may
     converge to a function that differs significantly from the function being
     projected (see [ernst2012]_).
     See :any:`functional_chaos` for more details on this topic.

OpenTURNS implements the following **specific orthonormal** univariate
polynomial families together with their associated distributions.

.. table::

    +--------------------------------------------------------------+---------------------------------------+
    | Distribution                                                 | Polynomial                            |
    +==============================================================+=======================================+
    | :class:`~openturns.Normal` :math:`\cN(\mu, \sigma)`          | :class:`~openturns.HermiteFactory`    |
    +--------------------------------------------------------------+---------------------------------------+
    | :class:`~openturns.Uniform` :math:`\cU(a, b)`                | :class:`~openturns.LegendreFactory`   |
    +--------------------------------------------------------------+---------------------------------------+
    | :class:`~openturns.Gamma` :math:`\Gamma(k, \lambda, \gamma)` | :class:`~openturns.LaguerreFactory`   |
    +--------------------------------------------------------------+---------------------------------------+
    | :class:`~openturns.Beta` :math:`B(\alpha, \beta, a, b)`      | :class:`~openturns.JacobiFactory`     |
    +--------------------------------------------------------------+---------------------------------------+
    | :class:`~openturns.Poisson` :math:`\cP(\lambda)`             | :class:`~openturns.CharlierFactory`   |
    +--------------------------------------------------------------+---------------------------------------+
    | :class:`~openturns.Binomial` :math:`\cB(n, p)`               | :class:`~openturns.KrawtchoukFactory` |
    +--------------------------------------------------------------+---------------------------------------+
    | :class:`~openturns.Polya` :math:`\cB^-(r, p)`                | :class:`~openturns.MeixnerFactory`    |
    +--------------------------------------------------------------+---------------------------------------+

For a distribution which admits a standard representative in the same
parametric family, the polynomial family is built for this **standard
representative**. The affine transformation
:math:`T(x) = a x + b` maps a random variable :math:`X` distributed
according to :math:`\mu` to its standard representative
:math:`Z = aX + b`. For example, if :math:`X \sim \cN(\mu, \sigma)`, its
standard representative is
:math:`Z = (X - \mu)/\sigma \sim \cN(0, 1)`. The polynomial :math:`P_n`
orthonormal with respect to :math:`\mu` is the composition of the
polynomial :math:`p_n` orthonormal with respect to the standard
representative :math:`\mu_0` and of the affine transformation :math:`T`:

.. math::

    P_n(x)\ =\ p_n(a x + b)\ =\ p_n \circ T(x).

Aside, OpenTURNS also implements generic algorithms for building orthonormal
univariate polynomial families with respect to any arbitrary probability
measure (implemented as a :class:`~openturns.Distribution`).
OpenTURNS implements the following :class:`~openturns.OrthonormalizationAlgorithm`\s,
with :class:`~openturns.AdaptiveStieltjesAlgorithm` as the default.

See also
--------
:any:`orthonormal_polynomials`, openturns.AdaptiveStieltjesAlgorithm

Examples
--------
>>> import openturns as ot
>>> import openturns.experimental as otexp

Build the specific orthonormal polynomial factory associated to the normal
distribution (Hermite):

>>> polynomial_factory = otexp.UniVariateDistributionPolynomialFactory(ot.Normal())
>>> for i in range(3):
...     print(polynomial_factory.build(i))
1
X
-0.707107 + 0.707107 * X^2

Build an orthonormal polynomial factory for the WeibullMin distribution with
the default orthonormalization algorithm:

>>> polynomial_factory = otexp.UniVariateDistributionPolynomialFactory(ot.WeibullMin())
>>> for i in range(3):
...     print(polynomial_factory.build(i))
1
-1 + X
1 - 2 * X + 0.5 * X^2

Build an orthonormal polynomial factory for the Weibull min distribution with
adaptive Stieltjes's orthonormalization algorithm:

>>> algorithm = ot.AdaptiveStieltjesAlgorithm(ot.WeibullMin())
>>> polynomial_factory = otexp.UniVariateDistributionPolynomialFactory(algorithm)
>>> for i in range(3):
...     print(polynomial_factory.build(i))
1
-1 + X
1 - 2 * X + 0.5 * X^2

Non-standard parameters trigger an affine transformation. For example,
a Normal distribution with :math:`\mu = 2.0` and :math:`\sigma = 3.0`:

>>> polynomial_factory = otexp.UniVariateDistributionPolynomialFactory(ot.Normal(2.0, 3.0))
>>> polynomial_factory.getHasSpecificFamily()
True
)RAW"

// ---------------------------------------------------------------------

%feature("docstring") OT::UniVariateDistributionPolynomialFactory::getHasSpecificFamily
"Accessor to the specific family boolean.

Returns
-------
hasSpecificFamily : bool
    True if the factory has a specific orthogonal polynomial family."

// ---------------------------------------------------------------------

%feature("docstring") OT::UniVariateDistributionPolynomialFactory::getOrthonormalizationAlgorithm
"Accessor to the orthonormalization algorithm.

Returns
-------
orthonormalizationAlgorithm : :class:`~openturns.OrthonormalizationAlgorithm`
    The univariate polynomial orthonormalization algorithm."

// ---------------------------------------------------------------------

%feature("docstring") OT::UniVariateDistributionPolynomialFactory::getSpecificFamily
"Accessor to the specific orthonormal polynomial family.

Returns
-------
specificFamily : :class:`~openturns.OrthogonalUniVariatePolynomialFamily`
    The specific orthonormal univariate polynomial family."
