name: Feature Request
description: Create a feature request.
labels:
  - enhancement
body:
  - type: textarea
    id: idea
    attributes:
      label: What is the idea?
      description: Describe what the feature is and the desired state.
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is this needed?
      description: Who would benefit from this feature? Why would this add value to them? What problem does this solve?
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Include any additional information that you think would be valuable.
