file (READ ${DOCSTRING_IN_FILE} DOCSTRING_IN_FILE_LINES)
string (REGEX REPLACE "\\\\" "\\\\\\\\\\\\\\\\" DOCSTRING_FILE_LINES "${DOCSTRING_IN_FILE_LINES}")
file (WRITE ${DOCSTRING_FILE} "${DOCSTRING_FILE_LINES}")
